#------------------------------------------------------------------------------
#
#  	          	    	Common makefile 
#
#	   		     	 Martin Dvorak
#				     1999
#------------------------------------------------------------------------------

# SWI Prolog path
PROLOG=pl

# TeX
TEX=cslatex

# C/C++
CC=gcc
CPP=g++
LINKER=gcc

# Java
JAVAC=jikes		
#JAVAC=guavac
#JAVAC=javac

#- EOF ------------------------------------------------------------------------
