# Auxiliary makefile

.PHONY=clean softclean

clean:
	rm -f *~ *.pd *.html source.pl; \
	rm -rf prolog hilex hilex.html prologdoc prologdoc.html library library.html; \
	cd doc; rm -f * ; true

softclean:
	rm -f *~ *.pd *.html; \
	rm -rf prolog hilex hilex.html prologdoc prologdoc.html library library.html; \
	cd doc; rm -f * ; true

# EOF
