PROGRAM ::=  COMMAND PROGRAM | COMMAND.
COMMAND ::= CLAUSE `.` | QUERY `.` | OPDECL `.`.
CLAUSE ::= FACT | RULE.
QUERY ::= `?-` QUERYBODY.
OPDECL ::= `:-op` `(` PRIORITY `,` ASOCIATIVITY `,` OPNAME `)` `.`.
FACT ::= HEAD.
RULE ::= HEAD `:-` RULEBODY.
HEAD ::= ATOM | STRUCTURE.
QUERYBODY ::= ALTERNATIVES.
ALTERNATIVEBODY ::= ALTERNATIVES.
ALTERNATIVES ::= HEAD `;` ALTERNATIVES | ALTERNATIVE.
PRIORITY ::= INTEGER.
ASOCIATIVITY ::= PRFASOC | POFASOC | INFASOC | LEFASOC | RIFASOC.
PRFASOC ::= `fx` | `fy`.
POFASOC ::= `xf` | `yf`.
INFASOC ::= `xfx` | `yfy`.
LEFASOC ::= `yfx`.
RIFASOC ::= `xfy`.
OPNAME ::= ATOM.
ATOM ::= LWRCHAR | LWRCHAR NONSPECIALCHARS | SPECIALCHARS | `'` CHARS `'`.
STRUCTURE ::= FUNCTOR `(` ARGUMENTS `)` | STRUCTWITHOP | LIST.
STRUCTWITHOP ::= PRFOP TERM | TERM POFOP | TERM INFOP TERM.
FUNCTOR ::=  ATOM | `.`.
ARGUMENTS ::= ARGUMENT `,` ARGUMENTS | ARGUMENT.
ARGUMENT ::= TERM.
CHAR ::= ALPHACHAR | NUMBERCHAR | SPECIALCHAR | `_`.
CHARS ::=  CHAR CHARS | CHAR.
NONSPECIALCHAR ::= ALPHACHAR | NUMBERCHAR | `_`.
NONSPECIALCHARS ::= NONSPECIALCHAR NONSPECIALCHARS | NONSPECIALCHAR.
ALPHACHAR ::= LWRCHAR | UPRCHAR.
NUMBERCHAR ::= `0`|`1`|`2`|`3`|`4`|`5`|`6`|`7`|`8`|`9`.
LWRCHAR ::= `a`|`b`|`c`|`d`|`e`|`f`|`g`|`h`|`i`|`j`|`k`|`l`|`m`|`n`|`o`|`p`|`q`|`r`|`s`|`t`|`u`|`v`|`w`|`x`|`y`|`z`.
UPRCHAR ::= `A`|`B`|`C`|`D`|`E`|`F`|`G`|`H`|`I`|`J`|`K`|`L`|`M`|`N`|`O`|`P`|`Q`|`R`|`S`|`T`|`U`|`V`|`W`|`X`|`Y`|`Z`.
SPECIALCHAR ::= `@`|`#`|`$`|`&`|`=`|`-`|`+`|`*`|`/`.
SPECIALCHARS ::= SPECIALCHAR SPECIALCHARS | SPECIALCHAR.
PRFOP ::= `?-`|`not`|`:-`|ATOM.
POFOP ::= ATOM.
INFOP ::= `:-`|ARIOP|`;`|`,`|RELOP|`is`|`=..`|`.`.
ARIOP ::= `+`|`-`|`*`|`/`|`mod`|`^`.
RELOP ::= `=`|`\=`|`<`|`=<`|`>`|`>=`|`=:=`|`=\=`|`==`|`\==`.
LIST ::= `[]` | EASYLIST | DIVIDEDLIST | TERM `.` LIST.
EASYLIST ::= `[` TERMS `]`.
DIVIDEDLIST ::= `[`  TERMS `|` TERMS `]`.
TERMS ::= TERM `,` TERMS | TERM.
TERM ::= ATOM | INTEGER | IDENTIFIER | STRUCTURE | LIST.
INTEGER ::= DIGIT INTEGER | DIGIT.
DIGIT ::= NUMBERCHAR.
IDENTIFIER ::= ATOM.
